### ISSUE TITLE
Use of an older version

### ISSUE THREAD

**Issue by gatk555** [transmitterdan/s2spice#7]
Hello,

[This discussion](https://sourceforge.net/p/ngspice/discussion/120973/thread/51228e0b01/) links to this repository.  Further down, there is a zipfile that contains what is probably an ancestor, s2spice.c.  I modified that as part of a prototype to make S-parameter subcircuits work in ngspice and would like to make it available in the discussion.  Since there are no attribution or license comments, my guess is that its legal status is by default "all rights reserved".  May I have your permission for this use? If so, would you like me to add such comments?

Thanks,

Giles

**Comment by transmitterdan** [comment]
Giles,

I don't understand what you are asking. If we speak about the program 's2spice.c' I did not write it, so I don't know anything about its permissions.

If I can see what you have done (feel free to post your code in this discussion) I can probably make this GUI style s2spice create code for ngspice.

I have recently observed that using G source instead of E source greatly speeds up simulation times for large S-parameter data-sets.  Thus, I have updated s2spice to use G rather than E.  I suspect ngspice would benefit from this change as well.  The number of nodes created are greatly reduced for large S-parameter data-sets.

**Comment by gatk555** [comment]
If the program was not yours, my request makes no sense.  It is attributed to Dan Dickey in that thread, and I guessed that meant you.

Many thanks for the offer, but it is probably not needed.  My code is still at the prototype stage, but if it makes it to release there will probably also be a change to the ngspice netlist parser to translate the Pspice syntax to native for both E and G.
At present I am just presenting it for discussion.

Thanks,

Giles

**Comment by transmitterdan** [comment]
Hi Giles,

I don't know what program you are speaking about. So, I am not sure who wrote it.  Can you give me a link so I can see exactly what you are asking about?
